### ISSUE TITLE
Hactoberfest Issue

### ISSUE THREAD

**Issue by sujayshanbhag** [sOR-o/DSA#6]
Hey @sOR-o the PR's are not getting accepted by hactoberfest. Did you sign up this repo for hactoberfest 2023? If yes, please add "hactoberfest-accepted" to the PR's before merging them.

**Comment by NikhilKalloli** [comment]
This repo is not signed up for hacktoberfest 2023.

**Comment by sujayshanbhag** [comment]
Hey there @NikhilKalloli, somehow earlier it was showing "not participating" on hactoberfest portfolio. As of yesterday it got accepted and is going through the review period. Thanks a ton man, you've been a great help :)

**Comment by NikhilKalloli** [comment]
Your Welcome @SujayShanbhag. Glad that you got it.
